import type { LevelConfig, BackgroundType } from './types';

export const LEVELS: LevelConfig[] = [
  {
    id: 1,
    name: 'The First Flight',
    background: 'samarkand' as BackgroundType,
    targetScore: 400,
    targetDistance: 600,
    scrollSpeed: 5,
    obstacleDensity: 380,
    obstacles: ['cloud', 'bird', 'minaret'],
    powerUps: [],
    description: 'Your first real flight! Dodge clouds and birds above Registan Square!',
  },
  {
    id: 2,
    name: 'The Gates of Khiva',
    background: 'khiva' as BackgroundType,
    targetScore: 900,
    targetDistance: 1000,
    scrollSpeed: 5.5,
    obstacleDensity: 280,
    obstacles: ['arch', 'minaret', 'bird'],
    powerUps: [],
    description: 'Stone arch walls and falcons block your path! Find the gaps to survive!',
  },
  {
    id: 3,
    name: 'Desert Winds',
    background: 'desert' as BackgroundType,
    targetScore: 1400,
    targetDistance: 1400,
    scrollSpeed: 6,
    obstacleDensity: 250,
    obstacles: ['arch', 'minaret', 'cloud', 'bird'],
    powerUps: ['shield'],
    description: 'Walls, clouds, and birds! The desert shows no mercy!',
  },
  {
    id: 4,
    name: 'Mountain Highs',
    background: 'mountains' as BackgroundType,
    targetScore: 1800,
    targetDistance: 1700,
    scrollSpeed: 6.5,
    obstacleDensity: 230,
    obstacles: ['arch', 'minaret', 'balloon', 'bird'],
    powerUps: ['shield'],
    description: 'Falcon flocks and floating balloons in tight mountain passes!',
  },
  {
    id: 5,
    name: "The Falcon's Path",
    background: 'samarkand' as BackgroundType,
    targetScore: 2200,
    targetDistance: 2000,
    scrollSpeed: 7,
    obstacleDensity: 200,
    obstacles: ['arch', 'minaret', 'bird', 'cloud'],
    powerUps: ['shield'],
    description: 'Birds hunt in packs! Arch walls shrink your escape routes!',
  },
  {
    id: 6,
    name: 'Magic Carpet Rush',
    background: 'desert' as BackgroundType,
    targetScore: 2800,
    targetDistance: 2600,
    scrollSpeed: 7.5,
    obstacleDensity: 190,
    obstacles: ['arch', 'minaret', 'cloud', 'balloon', 'bird'],
    powerUps: ['shield', 'speed'],
    description: 'All obstacles unite against you! Can you thread the needle?',
  },
  {
    id: 7,
    name: "The Weaver's Pattern",
    background: 'mountains' as BackgroundType,
    targetScore: 3400,
    targetDistance: 3300,
    scrollSpeed: 7.5,
    obstacleDensity: 240,
    obstacles: ['arch', 'minaret', 'bird', 'balloon', 'cloud'],
    powerUps: ['shield', 'magnet', 'speed'],
    description: 'Fast winds and weaving patterns! Speed is the real test!',
  },
  {
    id: 8,
    name: 'Oasis Mirage',
    background: 'khiva' as BackgroundType,
    targetScore: 4000,
    targetDistance: 3700,
    scrollSpeed: 8.5,
    obstacleDensity: 270,
    obstacles: ['arch', 'cloud', 'balloon', 'bird'],
    powerUps: ['shield', 'magnet', 'speed', 'tile'],
    description: 'The oasis blurs by! Reflexes over brute force!',
  },
  {
    id: 9,
    name: 'The Silk Road Gauntlet',
    background: 'desert' as BackgroundType,
    targetScore: 4800,
    targetDistance: 4100,
    scrollSpeed: 9.5,
    obstacleDensity: 300,
    obstacles: ['arch', 'bird', 'cloud', 'balloon'],
    powerUps: ['shield', 'magnet', 'speed', 'tile'],
    description: 'The ultimate speed test! How fast can you fly?',
  },
  {
    id: 10,
    name: 'Guardian of the Skies',
    background: 'samarkand' as BackgroundType,
    targetScore: 6000,
    targetDistance: 4500,
    scrollSpeed: 10.5,
    obstacleDensity: 330,
    obstacles: ['arch', 'bird', 'cloud', 'balloon'],
    powerUps: ['shield', 'magnet', 'speed', 'tile'],
    description: 'Only true masters survive the Guardian\'s speed!',
  },
];

export function getLevelConfig(levelId: number): LevelConfig {
  return LEVELS[levelId - 1] || LEVELS[0];
}
